import os
with open('sample.group','r') as f:
    sampledict = {}
    all_line = [line.strip() for line in f.readlines()]
    ALL_Groups = set()
    for a in all_line:
        group = a.split()[0]
        sample = a.split()[1]
        ALL_Groups.add(group)
        tn5 = sample
        if not group in sampledict:
            sampledict[group] = [tn5]
        else:
            sampledict[group].append(tn5)

CWD=os.getcwd()

rule all:
    input:
        expand("02.mapping/{groupname}.sort.markdup.merge.bam",groupname = ALL_Groups),
        expand("02.mapping/{groupname}.sort.markdup.merge.stat",groupname = ALL_Groups),
        expand("03.bigwig/{groupname}.sort.rmdup.merge.pair.bw",groupname = ALL_Groups),
        expand("05.Peakcalling/{groupname}_peaks.filterBL.bed",groupname = ALL_Groups),
        expand("04.TSS/{groupname}.tss.reference-point.heat.enrich.pdf",groupname = ALL_Groups),
        expand("06.QC/{groupname}.singlecell.qc.txt",groupname = ALL_Groups),
        expand("06.QC/{groupname}_fragments_barplot.pdf",groupname = ALL_Groups),
        expand("06.QC/{groupname}_violinplot.pdf",groupname = ALL_Groups),
        expand("06.QC/{groupname}_Unique{Frags}_FRiP{FRiP}.scatterplot.pdf",groupname = ALL_Groups,Frags=config['unique_frags'],FRiP=config['FRiP']),
        expand("06.QC/{groupname}_Unique{Frags}_FRiT{FRiT}.scatterplot.pdf",groupname = ALL_Groups,Frags=config['unique_frags'],FRiT=config['FRiT']),
        expand("07.singlecell/{groupname}_Unique{Frags}_FRiP{FRiP}_selected.singlecell.fragments.gz",groupname = ALL_Groups,Frags=config['unique_frags'],FRiP=config['FRiP']),
        expand("07.singlecell/{groupname}_Unique{Frags}_FRiT{FRiT}_selected.singlecell.fragments.gz",groupname = ALL_Groups,Frags=config['unique_frags'],FRiT=config['FRiT']),
        expand("07.singlecell/{groupname}_Unique{Frags}_selected.singlecell.fragments.gz",groupname = ALL_Groups,Frags=config['unique_frags']),

    output:
        "All.QC.txt"
    params:
        getbulkqc=config['scripts']['getbulkqc'],
        python_main=config['scripts']['python'],
    shell:
        "{params.python_main} {params.getbulkqc} {CWD}"

rule bwa_map:
    message: "do mapping"
    input:
        ref=config['ref'],
        r1="01.debarcoding/{sample}_S1_L001_R1_001.fastq.gz",
        r2="01.debarcoding/{sample}_S1_L001_R2_001.fastq.gz"
    
    threads: 20
    log: "log/{sample}.mem.log"

    params:
        rg=r"@RG\tID:{sample}\tSM:{sample}"

    output:
        bam="02.mapping/{sample}.sort.bam",
        bai="02.mapping/{sample}.sort.bam.bai"
    shell:  
        "bwa mem -R '{params.rg}' -k17 -t {threads} {input.ref} {input.r1} {input.r2} |samtools view -@ 5 - -b |samtools sort -m 2G -@ 5 - -o {output.bam} >& {log} && samtools index -@ 5 {output.bam}"
#rule index:
#    message: "indexing bam file"
#    input:
#        "02.mapping/{sample}.sort.bam"
#    log: "log/{sample}.index.log"    
#    threads: 20
#    output:
#        "02.mapping/{sample}.sort.bam.bai"
#    shell:
#        "samtools index -@ 5 {input}"

rule markdup:
    message: "mark duplicates"
    input:
        sortbam="02.mapping/{sample}.sort.bam",
        bai="02.mapping/{sample}.sort.bam.bai"
    log:
        "log/{sample}.markdup.log"
    output:
        markbam=temp("02.mapping/{sample}.sort.markdup.bam")
    threads: 3
    params:
        MarDup=config['scripts']['markdup'],
        python_main=config['scripts']['python']
    shell:
        "{params.python_main} {params.MarDup} -i {input.sortbam} -o {output.markbam} -n {wildcards.sample} -t pair >& {log}"

rule Merge:
    input:
         lambda wildcards: ["02.mapping/{sample}.sort.markdup.bam".format(sample=bam) for bam in sampledict[wildcards.groupname]]
    output:
        bam="02.mapping/{groupname}.sort.markdup.merge.bam",
        bai="02.mapping/{groupname}.sort.markdup.merge.bam.bai"
    log:
        "log/{groupname}.markdup.merge.log"
    threads: 10
    shell:
        "samtools merge -@ {threads} {output.bam} {input} >& {log} && samtools index -@ {threads} {output.bam}"

rule flagstat:
    message: "flagstat Merged bam file"
    input:
        "02.mapping/{groupname}.sort.markdup.merge.bam"
    threads: 10
    params:
        sambamba=config['scripts']['sambamba']
    output:
        "02.mapping/{groupname}.sort.markdup.merge.stat"
    shell:
        "{params.sambamba} flagstat -t {threads} {input} > {output}"

rule RmDup_and_Filter_LQ:
    message: "remove duplicates and filter low mapping quality and extract proper paired reads"
    input:
        bam="02.mapping/{groupname}.sort.markdup.merge.bam",
        bai="02.mapping/{groupname}.sort.markdup.merge.bam.bai"
    output:
        bam="02.mapping/{groupname}.sort.rmdup.merge.pair.bam",
        flagstat="02.mapping/{groupname}.sort.rmdup.merge.pair.bam.flagstat",
        bai="02.mapping/{groupname}.sort.rmdup.merge.pair.bam.bai"
    threads: 5
    params:
        Quality=config['quality'],
        sambamba=config['scripts']['sambamba']
    shell:
        "samtools view -f 0x2 -q {params.Quality} -F 3072 {input.bam} -b > {output.bam} && samtools index -@ 5 {output.bam}"
        " && {params.sambamba} flagstat -t 5 {output.bam} > {output.flagstat}"

rule Bigwig:
    message: "generate bigwig"
    input:
        bam="02.mapping/{groupname}.sort.rmdup.merge.pair.bam",
        bai="02.mapping/{groupname}.sort.rmdup.merge.pair.bam.bai"
    output:
        "03.bigwig/{groupname}.sort.rmdup.merge.pair.bw"
    threads: 40
    params:
        bamCoverage=config['scripts']['bamCoverage'],
    shell:
        "{params.bamCoverage} --bam {input.bam} --numberOfProcessors {threads} --outFileName {output} --normalizeUsing CPM"

rule TSS_enrichment:
    message: "generate TSS enrichment"
    input:
        "03.bigwig/{groupname}.sort.rmdup.merge.pair.bw"
    output:
        matgz="04.TSS/{groupname}.matrix_gene.mat.gz",
        tsspdf="04.TSS/{groupname}.tss.reference-point.heat.enrich.pdf"
    threads: 20
    params:
        anno=config['refanno'],
        computeMatrix=config['scripts']['computeMatrix'],
        plotHeatmap=config['scripts']['plotHeatmap']
    shell:
        "{params.computeMatrix} reference-point -S {input}"
                               " -R {params.anno}"
                               " --beforeRegionStartLength 3000"
                               " --afterRegionStartLength 3000"
                               " --binSize 10"
                               " --missingDataAsZero"
                               " --sortRegions descend" 
                               " --skipZeros -o {output.matgz} -p {threads} && "
        "{params.plotHeatmap} --matrixFile {output.matgz}"
        " --outFileName {output.tsspdf} --sortRegions no"
        " --colorMap Blues  --heatmapHeight 12 --legendLocation upper-left"
 
rule Sortbyname:
    input:
        bam="02.mapping/{groupname}.sort.rmdup.merge.pair.bam",
        bai="02.mapping/{groupname}.sort.rmdup.merge.pair.bam.bai"
    threads: 5
    params:
        sambamba=config['scripts']['sambamba']
    output:
        bam=temp("02.mapping/{groupname}.sortbyname.rmdup.merge.pair.bam"),
    shell:
        "{params.sambamba} sort -n -t 5 {input.bam} -o {output.bam}"


rule BamToFragments:
    input:
        bam="02.mapping/{groupname}.sortbyname.rmdup.merge.pair.bam",
    log:
        "log/{groupname}.bamtofragments.log"
    output:
        frag=temp("02.mapping/{groupname}.rmdup.merge.pair.fragments"),
        fragments=temp("02.mapping/{groupname}.rmdup.merge.pair.sort.fragments"),
        fragments2="02.mapping/{groupname}.rmdup.merge.pair.sort.fragments.gz",
        bam=temp("02.mapping/{groupname}.rmdup.merge.pair.singlcell.bam"),
        bam2="02.mapping/{groupname}.rmdup.merge.pair.singlcell.sort.bam"
    params:
        BamtoFrag=config['scripts']['BamtoFrag'],
        python_main=config['scripts']['python'],
        sambamba=config['scripts']['sambamba']
    shell:
        "{params.python_main} {params.BamtoFrag} -i {input.bam} -of {output.frag} -ob {output.bam} -m PE && bedtools sort -i {output.frag} > {output.fragments}"
        " && {params.sambamba} sort {output.bam} -o {output.bam2} && bgzip -c {output.fragments} > {output.fragments2}"

rule myindex:
    input:
        "02.mapping/{groupname}.rmdup.merge.pair.singlcell.sort.bam"
    threads: 20
    log:
        "log/{groupname}.rmdup.merge.pair.singlcell.sort.index.log"
    output:
        "02.mapping/{groupname}.rmdup.merge.pair.singlcell.sort.bam.bai"
    shell:
        "samtools index -@ 20 {input}"
        
rule Peakcalling:
    message: "run peak calling"
    input:
        "02.mapping/{groupname}.rmdup.merge.pair.sort.fragments"
    output:
        peaks="05.Peakcalling/{groupname}_peaks.narrowPeak",
        peakBL="05.Peakcalling/{groupname}_peaks.filterBL.bed"
    threads: 1
    params:
        aa="--nomodel  --shift 0 -q 0.01",
        gsize=config['gisze'],
        blacklist=config['blacklist']
    shell:
        "macs2  callpeak -t {input} -f BED"
        " -g {params.gsize} --outdir 05.Peakcalling/ -n {wildcards.groupname} {params.aa} && bedtools intersect "
        "-a 05.Peakcalling/{wildcards.groupname}_peaks.narrowPeak -b {params.blacklist} -v > 05.Peakcalling/{wildcards.groupname}_peaks.filterBL.bed && "
        " bedtools intersect -a 05.Peakcalling/{wildcards.groupname}_peaks.filterBL.bed -b {params.blacklist} -v > 05.Peakcalling/{wildcards.groupname}_peaks.filterBL.sort.bed && "
        "cat 05.Peakcalling/{wildcards.groupname}_peaks.filterBL.sort.bed |grep -v chrUn |grep -v GL |grep -v chrM|grep -v chrY > 05.Peakcalling/{wildcards.groupname}_peaks.filterBL.clean.sort.bed"


rule Get_FRiP_bam:
    message: "get the bam file within peak region"
    input:
        bam="02.mapping/{groupname}.sort.rmdup.merge.pair.bam",
        bai="02.mapping/{groupname}.sort.rmdup.merge.pair.bam.bai",
        peakBL="05.Peakcalling/{groupname}_peaks.filterBL.bed"
    output:
        bam=temp("02.mapping/{groupname}.sort.rmdup.merge.pair.withinpeaks.bam"),
        bai=temp("02.mapping/{groupname}.sort.rmdup.merge.pair.withinpeaks.bam.bai")
    shell:
        "samtools view -L {input.peakBL} {input.bam} -b > {output.bam} && samtools index {output.bam}"

rule Get_FRiT_bam:
    message: "get the bam file within tss region"
    input:
        bam="02.mapping/{groupname}.sort.rmdup.merge.pair.bam",
        bai="02.mapping/{groupname}.sort.rmdup.merge.pair.bam.bai",
        peakBL=config['tssbed']
    output:
        bam="02.mapping/{groupname}.sort.rmdup.merge.pair.withintss.bam",
        bai="02.mapping/{groupname}.sort.rmdup.merge.pair.withintss.bam.bai"
    shell:
        "samtools view -L {input.peakBL} {input.bam} -b > {output.bam} && samtools index {output.bam}"

rule Get_SingleCellQC:
    message: "get single cell qc statistics"
    input:
        bam="02.mapping/{groupname}.sort.markdup.merge.bam",
        bai="02.mapping/{groupname}.sort.markdup.merge.bam.bai",
        peakbam="02.mapping/{groupname}.sort.rmdup.merge.pair.withinpeaks.bam",
        tssbam="02.mapping/{groupname}.sort.rmdup.merge.pair.withintss.bam"
    log: 
        "log/{groupname}.GetSingleCellQC.log"
    output:
        txt="06.QC/{groupname}.singlecell.qc.txt"
    params:
        getQC=config['scripts']['getscQC'],
        python_main=config['scripts']['python'],
        Quality=config['quality']
    shell:
         "{params.python_main} {params.getQC} -b1 {input.bam} -b2 {input.peakbam} -b3 {input.tssbam} -o {output.txt} -q {params.Quality} >& {log}"

rule Plot_QC:
    message: "plot the single cell qc data with barplot and scatterplot"
    input:
        "06.QC/{groupname}.singlecell.qc.txt"
    output:
        bar="06.QC/{groupname}_fragments_barplot.pdf",
        violin="06.QC/{groupname}_violinplot.pdf",
        scatterplot="06.QC/{groupname}"+"_Unique{Frags}_FRiP{FRiP}.scatterplot.pdf".format(Frags=config['unique_frags'],FRiP=config['FRiP']),
        scatterplot2="06.QC/{groupname}"+"_Unique{Frags}_FRiT{FRiT}.scatterplot.pdf".format(Frags=config['unique_frags'],FRiT=config['FRiT']),
        Fragscellnames="06.QC/{groupname}"+"_Frags{Frags}_selected.cell.names".format(Frags=config['unique_frags']),
        cellnames="06.QC/{groupname}"+"_Unique{Frags}_FRiP{FRiP}_selected.cell.names".format(Frags=config['unique_frags'],FRiP=config['FRiP']),
        cellnames2="06.QC/{groupname}"+"_Unique{Frags}_FRiT{FRiT}_selected.cell.names".format(Frags=config['unique_frags'],FRiT=config['FRiT']),
    params:
        Rscript=config['scripts']['Rscript'],
        plotqc=config['scripts']['plotqc'],
        FRiP=config['FRiP'],
        FRiT=config['FRiT'],
        Frags=config['unique_frags']
    shell:
        "{params.Rscript} {params.plotqc} -i {input} -p {params.FRiP} -t {params.FRiT} -n {params.Frags} -o 06.QC/{wildcards.groupname}"

rule Extract_Cell:
    message: "extract the possible cells based on qc table"
    input:
        Fragscellname="06.QC/{groupname}"+"_Frags{Frags}_selected.cell.names".format(Frags=config['unique_frags']),
        FRiPcellnames="06.QC/{groupname}"+"_Unique{Frags}_FRiP{FRiP}_selected.cell.names".format(Frags=config['unique_frags'],FRiP=config['FRiP']),
        FRiTcellnames="06.QC/{groupname}"+"_Unique{Frags}_FRiT{FRiT}_selected.cell.names".format(Frags=config['unique_frags'],FRiT=config['FRiT']),
        fragments="02.mapping/{groupname}.rmdup.merge.pair.sort.fragments.gz",
        bamcell="02.mapping/{groupname}.rmdup.merge.pair.singlcell.sort.bam",
        bamcellbai="02.mapping/{groupname}.rmdup.merge.pair.singlcell.sort.bam.bai"
    output:
        selectedbam_f_sort="07.singlecell/{groupname}"+"_Unique{Frags}_selected.singlecell.sort.bam".format(Frags=config['unique_frags'],FRiP=config['FRiP']),
        selectedbam_f_sort_bai="07.singlecell/{groupname}"+"_Unique{Frags}_selected.singlecell.sort.bam.bai".format(Frags=config['unique_frags'],FRiP=config['FRiP']),
        selectedfrags_f=temp("07.singlecell/{groupname}"+"_Unique{Frags}_selected.singlecell.fragments".format(Frags=config['unique_frags'])),
        selectedfrags2_f="07.singlecell/{groupname}"+"_Unique{Frags}_selected.singlecell.fragments.gz".format(Frags=config['unique_frags']),
        
        selectedbam_sort="07.singlecell/{groupname}"+"_Unique{Frags}_FRiP{FRiP}_selected.singlecell.sort.bam".format(Frags=config['unique_frags'],FRiP=config['FRiP']),
        selectedbam_sort_bai="07.singlecell/{groupname}"+"_Unique{Frags}_FRiP{FRiP}_selected.singlecell.sort.bam.bai".format(Frags=config['unique_frags'],FRiP=config['FRiP']),
        selectedfrags=temp("07.singlecell/{groupname}"+"_Unique{Frags}_FRiP{FRiP}_selected.singlecell.fragments".format(Frags=config['unique_frags'],FRiP=config['FRiP'])),
        selectedfrags2="07.singlecell/{groupname}"+"_Unique{Frags}_FRiP{FRiP}_selected.singlecell.fragments.gz".format(Frags=config['unique_frags'],FRiP=config['FRiP']),
        
        selectedbam_t_sort="07.singlecell/{groupname}"+"_Unique{Frags}_FRiT{FRiT}_selected.singlecell.sort.bam".format(Frags=config['unique_frags'],FRiT=config['FRiT']),
        selectedbam_t_sort_bai="07.singlecell/{groupname}"+"_Unique{Frags}_FRiT{FRiT}_selected.singlecell.sort.bam.bai".format(Frags=config['unique_frags'],FRiT=config['FRiT']),
        selectedfrags_t=temp("07.singlecell/{groupname}"+"_Unique{Frags}_FRiT{FRiT}_selected.singlecell.fragments".format(Frags=config['unique_frags'],FRiT=config['FRiT'])),
        selectedfrags2_t="07.singlecell/{groupname}"+"_Unique{Frags}_FRiT{FRiT}_selected.singlecell.fragments.gz".format(Frags=config['unique_frags'],FRiT=config['FRiT']),
   
    params:
        extractcell=config['scripts']['extractcell'],
        python_main=config['scripts']['python'],
        Quality=config['quality'],
        sambamba=config['scripts']['sambamba']
   # run:
      #  f = open(input.Fragscellname,'r')
      #  if len([line.strip() for line in f.readlines()]) > 100:
    shell:
        "{params.python_main} {params.extractcell} -n {input.FRiPcellnames}  -f {input.fragments} "
        "-b {input.bamcell} -ob {output.selectedbam} -of {output.selectedfrags} && bgzip -c {output.selectedfrags} > {output.selectedfrags2}"
        " && {params.sambamba} sort -t 5 {output.selectedbam} -o {output.selectedbam_sort} && {params.sambamba} index -t 5 {output.selectedbam_sort} && "

        " {params.python_main} {params.extractcell} -n {input.FRiTcellnames}  -f {input.fragments} "
        "-b {input.bamcell} -ob {output.selectedbam_t} -of {output.selectedfrags_t} && bgzip -c {output.selectedfrags_t} > {output.selectedfrags2_t}"
        " && {params.sambamba} sort -t 5 {output.selectedbam_t} -o {output.selectedbam_t_sort} && {params.sambamba} index -t 5 {output.selectedbam_t_sort} && "

        " {params.python_main} {params.extractcell} -n {input.Fragscellname}  -f {input.fragments} "
        "-b {input.bamcell} -ob {output.selectedbam_f} -of {output.selectedfrags_f} && bgzip -c {output.selectedfrags_f} > {output.selectedfrags2_f}"
        " && {params.sambamba} sort -t 5 {output.selectedbam_f} -o {output.selectedbam_f_sort} && {params.sambamba} index -t 5 {output.selectedbam_f_sort}"


